### PR TITLE
storage: move proto to api repo

### PR DESCRIPTION
**Pull request by glimchb**
Now lives here https://github.com/opiproject/opi-api/tree/main/storage/proto

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by glimchb** [comment]
related to https://github.com/opiproject/opi-api/pull/45

**Comment by glimchb** [comment]
getting this error now
```
server.go:11:2: no required module provides package github.com/opiproject/opi-api/storage/proto; to add it:
        go get github.com/opiproject/opi-api/storage/proto
```

**Review by seroyer — APPROVED** [review]
lgtm

**Comment by glimchb** [comment]
merging this and posting new draft so @mestery can review there

**Pull request merged**
