### PR TITLE
IPSec offload on Marvell DPU with gRPC

### PR DESCRIPTION
**Pull request by bbhamidipati**
This demo shows configuration of Marvell DPU for IPsec offload using gRPC. The data path is based on HW accelerated VPP and leverages Ligato for off-chip configuration.

### CODE REVIEW

**Comment by bbhamidipati** [comment]
We want to upload our grpc based IPSec configuration.

**Review by glimchb — CHANGES_REQUESTED** [review]
how this is aligned with 
- https://github.com/opiproject/opi-strongswan-bridge implementation  ?
- and API protobuf definitions https://github.com/opiproject/opi-api/blob/main/security/v1/ipsec.proto ?

**Comment by vijayinavolu** [comment]
> how this is aligned with
> 
> * https://github.com/opiproject/opi-strongswan-bridge implementation  ?
> * and API protobuf definitions https://github.com/opiproject/opi-api/blob/main/security/v1/ipsec.proto ?

This demo shows Marvell's current way of providing offchip IPsec offload configuration with gRPC, shared it as reference. We will next submit a demo that we are working on which is aligned with current OPI strongswan way.

**Comment by glimchb** [comment]
> > how this is aligned with
> > 
> > * https://github.com/opiproject/opi-strongswan-bridge implementation  ?
> > * and API protobuf definitions https://github.com/opiproject/opi-api/blob/main/security/v1/ipsec.proto ?
> 
> This demo shows Marvell's current way of providing offchip IPsec offload configuration with gRPC, shared it as reference. We will next submit a demo that we are working on which is aligned with current OPI strongswan way.

If this demo is unrelated to OPI approved APIs and strongswan app - this needs to be clearly documented on this page.

Personally I see no value publishing demos in OPI that just confuse users and customers with non-approved ways of doing things.

**Comment by mgheorghe** [comment]
" OPI approved APIs and strongswan app "
I thought the requirement is the OPI API only, strongswan not being a requirement. strongswan is just one implementation but in the end as long as the API matches anything could be underneath to provide same functionality.

**Comment by vijayinavolu** [comment]
> > > how this is aligned with
> > > 
> > > * https://github.com/opiproject/opi-strongswan-bridge implementation  ?
> > > * and API protobuf definitions https://github.com/opiproject/opi-api/blob/main/security/v1/ipsec.proto ?
> > 
> > 
> > This demo shows Marvell's current way of providing offchip IPsec offload configuration with gRPC, shared it as reference. We will next submit a demo that we are working on which is aligned with current OPI strongswan way.
> 
> If this demo is unrelated to OPI approved APIs and strongswan app - this needs to be clearly documented on this page.
> 
> Personally I see no value publishing demos in OPI that just confuse users and customers with non-approved ways of doing things.

It's ok if not published. SInce OPI slack channel retention is only for 30 days, we shared it here for reference

**Comment by vijayinavolu** [comment]
> " OPI approved APIs and strongswan app " I thought the requirement is the OPI API only, strongswan not being a requirement. strongswan is just one implementation but in the end as long as the API matches anything could be underneath to provide same functionality.

Yes, Since we are also planning a demo with strongswan I mentioned it.

**Comment by glimchb** [comment]
> " OPI approved APIs and strongswan app " I thought the requirement is the OPI API only, strongswan not being a requirement. strongswan is just one implementation but in the end as long as the API matches anything could be underneath to provide same functionality.

@mgheorghe yes, I agree. thanks for clarification.
if Marvell @vijayinavolu already `planning a demo with strongswan` I think it will be valuable to see it

**Comment by bbhamidipati** [comment]
> 

Can you please suggest a folder for Marvell and appropriate folder name? We will build future demo using this folder as base.

**Comment by glimchb** [comment]
@bbhamidipati also please rename the file name extension to be `.md` instead of `.txt`

**Comment by glimchb** [comment]
Merged #686 instead

**Comment by glimchb** [comment]
> Yes, Since we are also planning a demo with strongswan I mentioned it.

@vijayinavolu when is your planned strongswan demo ?

**Pull request closed without merging**
