### PR TITLE
Security: Test added for traffic over the IPsec tunnel.

### PR DESCRIPTION
**Pull request by vikumarks**
* Updated test script to use CyPerf as traffic
* Update README.md
Signed-off-by: Vinod Kumar <vikumarks@gmail.com>

### CODE REVIEW

**Review by mgheorghe — APPROVED** [review]

**Comment by sandersms** [comment]
@vikumarks Please correct the DCO, Commitlint, and markdown-lint errors so the submission can be reviewed.

**Comment by vikumarks** [comment]
Signed-off-by: Vinod Kumar <vikumarks@gmail.com>

**Comment by vikumarks** [comment]
> @vikumarks Please correct the DCO, Commitlint, and markdown-lint errors so the submission can be reviewed.

Fixed

**Comment by sandersms** [comment]
> > @vikumarks Please correct the DCO, Commitlint, and markdown-lint errors so the submission can be reviewed.
> 
> Fixed

The commitlint and markdown-lint are still failing.  The markdown-lint needs to be fixed to allow a merge/review to be completed.  You can look at the details of the failure to resolve the problem.

**Comment by vikumarks** [comment]
> > > @vikumarks Please correct the DCO, Commitlint, and markdown-lint errors so the submission can be reviewed.
> > 
> > 
> > Fixed
> 
> The commitlint and markdown-lint are still failing. The markdown-lint needs to be fixed to allow a merge/review to be completed. You can look at the details of the failure to resolve the problem.



> > > @vikumarks Please correct the DCO, Commitlint, and markdown-lint errors so the submission can be reviewed.
> > 
> > 
> > Fixed
> 
> The commitlint and markdown-lint are still failing. The markdown-lint needs to be fixed to allow a merge/review to be completed. You can look at the details of the failure to resolve the problem.

Fixed

**Comment by vikumarks** [comment]
@sandersms All checks have passed.

**Review by sandersms — APPROVED** [review]
LGTM

**Pull request merged**
