### PR TITLE
CI: add docekrfile hadolint

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Review by seroyer — APPROVED** [review]
That's pretty nice.  I'm not entirely sold on the dnf package version rule.  I don't think we care about the package versions on most of these packages.  If we do specify the package version, does dependabot catch when they are old?

**Comment by glimchb** [comment]
> That's pretty nice. I'm not entirely sold on the dnf package version rule. I don't think we care about the package versions on most of these packages. If we do specify the package version, does dependabot catch when they are old?



> That's pretty nice. I'm not entirely sold on the dnf package version rule. I don't think we care about the package versions on most of these packages. If we do specify the package version, does dependabot catch when they are old?

disabled it for now, will read on dependabot inside dockerfiles...

**Review by mestery — APPROVED** [review]
Fascinating, good find!

**Comment by glimchb** [comment]
failed on access
```
2022-07-12T22:35:50.7812659Z [91mfatal: unable to access 'https://github.com/spdk/isa-l.git/': Failed to connect to github.com port 443 after 130430 ms: Connection timed out
```

**Pull request merged**
