### PR TITLE
storage: add go dockers and separate go modules

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Review by mestery — APPROVED** [review]
Seems reasonable and I was thinking of doing the same for security.

**Comment by mestery** [comment]
Did you want to update the docker-compose as well to use the new Dockerfiles?

**Comment by glimchb** [comment]
@mestery will update docker-compose to use new images instead of building them

**Comment by glimchb** [comment]
@mestery attempt on compose change is here #260

**Pull request merged**
