### PR TITLE
storage: split client into files

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by seroyer** [comment]
Maybe this is only for testing purposes and is fine, but should the client have direct access to middle/backend?

**Comment by seroyer** [comment]
Perhaps we should add a linter for golang.

**Comment by glimchb** [comment]
> Maybe this is only for testing purposes and is fine, but should the client have direct access to middle/backend?

this is just testing APIs

**Review by mestery — APPROVED** [review]
This seems fine because it mostly moves code around. Nice work!

**Pull request merged**
