### PR TITLE
security: ci: always collect logs

### PR DESCRIPTION
**Pull request by seroyer**
Fixes: #322

Signed-off-by: Steven Royer <sroyer@redhat.com>

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
by design if everything is success I didn't want to collect logs... since nobody looks at them... so time and space savings...

**Comment by seroyer** [comment]
> by design if everything is success I didn't want to collect logs... since nobody looks at them... so time and space savings...

@mestery opened the issue, I think because I noted I didn't see a test run for a particular PR.  That's because the output of the test was in the logs and wasn't getting saved.  But I'd be happy to revisit this.

**Review by mestery — APPROVED** [review]
I'm fine with this. Storage is infinite from our perspective.

**Comment by glimchb** [comment]
approved

**Pull request merged**
