### PR TITLE
compose: Split up networking

### LINKED ISSUE #116: Split out networking in docker compose setup
We currently have a single network for all components. We should expand this to create multiple docker networks and isolate things where it makes sense. Ideally, we would want at least two networks:
* xPU network for xPU CPU and xPU BMC
* External network for external components

### PR DESCRIPTION
**Pull request by mestery**
This commit creates 2 additional docker networks:
* bmc
* opi-external

It moves the various containers onto the appropriate networks and
adjusts the test commands to pass with the new setup.

Finally, I've updated the diagram to reflect the new reality.

Closes #116

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
Suggestions on network names welcome 🤣

**Review by pdp2shirts — COMMENTED** [review]
in the diagram you added there are now two xPU CPU interfaces, both of which have a .7 address. is that what you intended?, OK I see that you placed one interface on the opi network and one on the opi-external network.

**Comment by mestery** [comment]
Yes because the xPU is now on multiple networks.

**Review by glimchb — CHANGES_REQUESTED** [review]
- `opi-external` is confusing... this is our high-speed 100G for exampoe network if I understand correctly... what is the official name for this?
- `bmc` network is ok name, I understand that this is our 1G management network
- what is `opi` network then?

**Comment by mestery** [comment]
> * `opi-external` is confusing... this is our high-speed 100G for exampoe network if I understand correctly... what is the official name for this?
> * `bmc` network is ok name, I understand that this is our 1G management network
> * what is `opi` network then?

I agree, the naming is bad, but at least we're not doing [cache invalidation](https://martinfowler.com/bliki/TwoHardThings.html).

How about this for names:
* bmc: Provisioning network
* xpu-cpu: Network for xPU CPU components
* high-speed-external: 100G/200G/400G high speed network

**Review by glimchb — APPROVED** [review]
great work!

**Pull request merged**
