### PR TITLE
Add OPI Storage Sequence Diagram

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by glimchb** [comment]
@yadong2007 @llabordehpe @PWAlessi - does it help ?

**Review by mestery — APPROVED** [review]

**Comment by glimchb** [comment]
> Don't you want to use in the diagram the methods defined in the protobufs? For example, shouldn't "Backend-Nvme-TCP-Connect" be "NVMfRemoteControllerConnect" ?

Sure, good suggestion, I can do that, but his wasn't suppose to be exact definition of API calls, just a sequence diagram...

> And "bdev_nvme_attach_controller" isn't really called on the remote storage, but called by the local SPDK shim to local SPDK NVMe/TCP initiator when handling NVMfRemoteControllerConnect().
> So maybe the vertical line/entity xDPU/SPDK should be broken in two, with an SPDK-Shim line and an SPDK-NVMe/TCP-initiator line.

I don't want to split the entities in this diagram, because we have the split already on the block diagram.
This one just suppose to show a sequence of calls/events... That's why also I show that `bdev_nvme_attach_controller` kinda called on target... It's not suppose to be 100% accurate, just explain the thinking and flow...

> For the middleend "bdev_crypto_create", if it is supposed to deal with at-rest encryption, shouldn't it be issued on the NVMe/TCP server where the data actually resides ?

No. the encryption/compression happens in DPU/IPU itself using HW acceleration or SW based resources. If there is an encryption/compression/raid in the backend real storage where the data is - this is out of OPI scope...

**Review by intelfisz — COMMENTED** [review]
@glimchb - thanks for contributing the diagram! Some comments related to the diagram:
- What is meant by 'missing from SPDK'? You can create NVMe subsystems there
- It is "one CSI client" interfacing both front- and backend - do you mean CSI controller and node drivers? Split?
- Use e.g. for 'for example' and i.e. for 'specification'
- For backend, connection cannot take place before frontend infra is ready. Rename?
- For crypto do you encapsulate the key in the object and pass it around? On backend same key need to be used as when attaching the volume for IPU-side DARE crypto.
- You use 'scsi' as an example to show the possibility that it does not always need to be NVMe-related further down in the SPDK SW-stack processing? I find it actually confusing without explanation. For a first example it may be beneficial to stick to a simple use case.

**Comment by glimchb** [comment]
> @glimchb - thanks for contributing the diagram! Some comments related to the diagram:

sure @intelfisz . Please consider this diagram as first draft and shared. You and others can propose any changes to it as you see fit. I created it using https://draw.io/ so we can all collaborate and change it together.

> * What is meant by 'missing from SPDK'? You can create NVMe subsystems there

you can create NVMeoF subsystems in SPDK, not NVMe/PCIe yet... https://spdk.io/doc/vhost.html

> * It is "one CSI client" interfacing both front- and backend - do you mean CSI controller and node drivers? Split?

same. no split. see more on CSI here https://github.com/opiproject/opi-api/blob/main/storage/opi-csi.md
I didn't want to deep dive in CSI on this page.

> * Use e.g. for 'for example' and i.e. for 'specification'
ok

> * For backend, connection cannot take place before frontend infra is ready. Rename?
why not? BE connection to remote storage e.g. `bdev_nvme_attach_controller` can happen before nvme/virtio presentatino is ready on the FE.

> * For crypto do you encapsulate the key in the object and pass it around? On backend same key need to be used as when attaching the volume for IPU-side DARE crypto.

I don't know yet, our Crypto APIs are still empty https://github.com/opiproject/opi-api/blob/main/storage/v1/middleend.proto
If you can contribute something it would be great. 
There is example how AMD proposed to do it here `NvmeNsCryptoSvc` https://github.com/opiproject/opi-api/pull/133

> * You use 'scsi' as an example to show the possibility that it does not always need to be NVMe-related further down in the SPDK SW-stack processing? I find it actually confusing without explanation. For a first example it may be beneficial to stick to a simple use case.

Sure, for FE we can use **Nvme** [pci, tcp, rdma] or **Virtio** [blk, scsi, fs]. I wanted to illustrate the difference

**Pull request merged**
