### PR TITLE
renovate: hold fedora images to 37

### PR DESCRIPTION
**Pull request by seroyer**
Signed-off-by: Steven Royer <sroyer@redhat.com>

### CODE REVIEW

**Comment by seroyer** [comment]
If this works, is it better or worse than just -1 on the chore PR or outright closing the chore PR for the next 5 or so months until 38 is actually released?

**Comment by mestery** [comment]
I'm still confused as to why Renovate is trying to update to Fedora 38 if it's not released yet. 🤷

**Review by mestery — APPROVED** [review]
I'm fine with this for now, though we should file an Issue to track removing this once Fedora 38 is released.

**Comment by seroyer** [comment]
> I'm still confused as to why Renovate is trying to update to Fedora 38 if it's not released yet. shrug

It's annoying, but it's because Fedora has tagged 38 images which == rawhide.  This seems to be relatively new behavior.  I don't think the 37 tag was created nearly this early in the cycle.

**Review by glimchb — CHANGES_REQUESTED** [review]
we can just close renovate PR and it will not suggest to upgrade this again until we manualyl re-trigger via issue #403

**Comment by seroyer** [comment]
> we can just close renovate PR and it will not suggest to upgrade this again until we manualyl re-trigger via issue #403

I think I agree as long as all maintainers understand that a renovate update to a base image needs to be carefully considered and not just rubber stamped and merged.

**Pull request closed without merging**
